name: Publish package
on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'
      - run: npm ci
      - run: npm version ${{ github.event.release.tag_name }} --workspaces
      - run: npm run build --workspaces --if-present
      - run: npm publish --access public --workspaces
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create bump version PR
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Bump version ${{ github.event.release.tag_name }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: release-${{ github.event.release.tag_name }}
          base: master
          delete-branch: true
          title: '[Release] ${{ github.event.release.tag_name }}'
          assignees: lamo2k123
          reviewers: lamo2k123
          draft: false
